### PR TITLE
Add deployment via CI on osx

### PR DESCRIPTION
**Pull request by k-dominik**
Hi @constantinpape,

I added the deployment for osx via travis (and conda packages for linux) with this PR. I also tried using the windows machines from travis ci but didn't get that to work (hence there is #35).

Same here, I'll later tag the tip of this pr to trigger the deployment - will insert a linke here once it's done. [link to build](https://travis-ci.org/github/k-dominik/covid-if-annotations/builds/697357304)

Before mergin, again, I would remove the bumpversion commit, and remove all build packages.

btw, I haven't tested the binaries yet :D

### CODE REVIEW

**Comment by k-dominik** [comment]
Just checked the binary - it works.

**Review by constantinpape — APPROVED** [review]

**Comment by constantinpape** [comment]
> Just checked the binary - it works.

Ok, should I merge or do you need to change anything else here?

**Comment by k-dominik** [comment]
This can be merged. The windows build seems now also to work (will know for sure in 30 minutes). After that is merged, too, I'd suggest to setup CI, probably from your account (I don't think I can do it for the hci org).

**Comment by constantinpape** [comment]
> This can be merged. The windows build seems now also to work (will know for sure in 30 minutes). After that is merged, too, I'd suggest to setup CI, probably from your account (I don't think I can do it for the hci org).

Sounds good.

**Pull request merged**
